---
swagger: '2.0'
info:
  version: 0.2.0
  title: Caliopen HTTP/REST API
schemes:
- http
host: localhost:31415
basePath: "/api"
paths:
## user ##
  "/v1/authentications":
    "$ref": paths/authentications.yaml#/authentications
  "/v1/me":
    "$ref": paths/me.yaml#/me
  "/v1/users":
    "$ref": paths/users.yaml#/users
  "/v2/users/{user_id}":
    "$ref": paths/users.yaml#/users_{user_id}
  "/v2/users/{user_id}/actions":
    "$ref": paths/users.yaml#/users_{user_id}_actions
  "/v2/username/isAvailable":
    "$ref": paths/users.yaml#/users_isAvailable
  "/v1/settings":
     "$ref": paths/settings.yaml#/settings
  "/v2/identities/locals":
    "$ref": paths/identities.yaml#/identities_locals
  "/v2/identities/remotes":
    "$ref": paths/identities.yaml#/identities_remotes
  "/v2/identities/remotes/{identifier}":
    "$ref": paths/identities.yaml#/identities_remotes_{identifier}
  "/v2/passwords/reset":
    "$ref": paths/passwords.yaml#/passwords_reset
  "/v2/passwords/reset/{token}":
    "$ref": paths/passwords.yaml#/passwords_reset_{token}
  "/v2/providers":
    "$ref": paths/providers.yaml#/providers
  "/v2/providers/{provider_name}":
    "$ref": paths/providers.yaml#/providers_{provider_name}
  "/v2/providers/{provider_name}/callback":
    "$ref": paths/providers.yaml#/providers_{provider_name}_callback
  "/v2/test/oauth":
    "$ref": paths/providers.yaml#/oauth_test
## contacts ##
  "/v1/contacts":
    "$ref": paths/contacts.yaml#/contacts
  "/v1/contacts/{contact_id}":
    "$ref": paths/contacts.yaml#/contacts_{contact_id}
  "/v2/contacts":
    "$ref": paths/contactsV2.yaml#/contacts
  "/v2/contacts/{contact_id}":
    "$ref": paths/contactsV2.yaml#/contacts_{contact_id}
  "/v2/contacts/{contact_id}/identities":
    "$ref": paths/contactsV2.yaml#/contacts_{contact_id}_identities
  "/v2/contacts/{contact_id}/publickeys":
    "$ref": paths/contactsV2.yaml#/contacts_{contact_id}_publickeys
  "/v2/contacts/{contact_id}/publickeys/{pubkey_id}":
    "$ref": paths/contactsV2.yaml#/contacts_{contact_id}_publickeys_{pubkey_id}
  "/v2/contacts/{contact_id}/tags":
    "$ref": paths/contactsV2.yaml#/contacts_{contact_id}_tags
  "/v1/imports":
    "$ref": paths/imports.yaml#/imports
## messages/discussions ##
  "/v1/discussions":
    "$ref": paths/discussions.yaml#/discussions
  "/v1/discussions/{discussion_id}":
    "$ref": paths/discussions.yaml#/discussions_{discussion_id}
  "/v1/messages":
    "$ref": paths/messages.yaml#/messages
  "/v2/messages":
    "$ref": paths/messagesV2.yaml#/messages
  "/v1/messages/{message_id}":
    "$ref": paths/messages.yaml#/messages_{message_id}
  "/v2/messages/{message_id}":
    "$ref": paths/messagesV2.yaml#/messages_{message_id}
  "/v2/messages/{message_id}/tags":
    "$ref": paths/messagesV2.yaml#/messages_{message_id}_tags
  "/v2/messages/{message_id}/actions":
    "$ref": paths/messagesV2.yaml#/messages_{message_id}_actions
  "/v2/messages/{message_id}/attachments":
    "$ref": paths/messagesV2.yaml#/messages_{message_id}_attachments
  "/v2/messages/{message_id}/attachments/{attachment_id}":
    "$ref": paths/messagesV2.yaml#/messages_{message_id}_attachments_{attachment_id}
  "/v1/raws/{raw_msg_id}":
    "$ref": paths/raws.yaml#/raws_{raw_msg_id}
## tags ##
  "/v2/tags":
    "$ref": paths/tags.yaml#/tags
  "/v2/tags/{tag_id}":
    "$ref": paths/tags.yaml#/tags_{tag_id}
## devices ##
  "/v2/devices":
    "$ref": paths/devices.yaml#/devices
  "/v2/devices/{device_id}":
    "$ref": paths/devices.yaml#/devices_{device_id}
  "/v2/devices/{device_id}/actions":
    "$ref": paths/devices.yaml#/devices_{device_id}_actions
  "/v2/validate-device/{token}":
    "$ref": paths/devices.yaml#/validate_device_{token}
  ## search/suggest ##
  "/v2/participants/suggest":
    "$ref": paths/participants.yaml#/participants_suggest
  "/v1/participants/discussion":
    "$ref": paths/participants.yaml#/participants_discussion

  "/v2/search":
    "$ref": paths/search.yaml#/search
## notifications
  "/v2/notifications":
    "$ref": paths/notifications.yaml#/notifications

securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. `Password` is the `access_token` return
      by /authentications and `Username` is the `user_id` returned by /authentications
