version: '2'
services:
  # Caliopen APIv2
  api:
      build: ../src/backend/interfaces/REST/go.server
      links:
          - apiv1:apiv1.dev.caliopen.org
          - redis:redis.dev.caliopen.org
          - cassandra:cassandra.dev.caliopen.org
          - nats:nats.dev.caliopen.org
      ports:
          - "31415:31415"

  # Caliopen APIv1
  apiv1:
      build: ../src/backend/interfaces/REST/py.server
      links:
          - redis:redis.dev.caliopen.org
          - cassandra:cassandra.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
      ports:
          - "6543:6543"

  # ### Redis Database
  #
  # Used to store sessions.
  redis:
      image: redis
      ports:
          - "6379:6379"

  # ### Cassandra
  #
  # Cassandra is used as the reference storage for business data
  cassandra:
      image: cassandra:3.0
      ports:
          - "9042:9042"
          - "9160:9160"
          - "7000:7000"
      volumes:
          - .data/cassandra:/var/lib/cassandra

  # ### Elasticsearch
  #
  # Used to index mail content and ensure great research performances.
  elasticsearch:
      image: elasticsearch:2
      ports:
          - "9200:9200"
      volumes:
          - .data/elasticsearch/data:/usr/share/elasticsearch/data

  # Caliopen cli tool
  cli:
      build: ../src/backend/tools/py.CLI
      links:
          - cassandra:cassandra.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
      environment:
          CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1

  # Caliopen frontend
  frontend:
      build: ../src/frontend/web_application
      links:
          - api:api.dev.caliopen.org
      ports:
        - "4000:4000"
  # Broker
  broker:
      build: ../src/backend/protocols/go.smtp
      links: 
          - cassandra:cassandra.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
          - nats:nats.dev.caliopen.org
          
      ports:
        - "2525:2525"
  # NATS
  nats:
      image: nats:0.9.6
      ports:
          - "4222:4222"

  # Message Handler
  message_handler:
      build: ../src/backend/interfaces/NATS/py.client
      links:
          - cassandra:cassandra.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
          - nats:nats.dev.caliopen.org
