version: '2.1'
volumes:
  index:
    driver: local
  db:
    driver: local
  store:
    driver: local

services:
  # Proxy API
  proxyapi:
    image: nginx
    depends_on:
      - apiv2
      - apiv1
    ports:
      - "31415:31415"
    volumes:
      - ./conf/proxy-api.conf:/etc/nginx/nginx.conf
  # Caliopen APIv2
  apiv2:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.go-api
    image: caliopen_apiv2
    ## this very bad config for a public machine
    depends_on:
      - redis
      - cassandra
      - elasticsearch
      - nats
      - objectstore
    ports:
      - "6544:6544"
    volumes:
      - ../src/backend/configs:/etc/caliopen
  # Caliopen APIv1
  apiv1:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.py-api
    image: caliopen_apiv1
    depends_on:
      - redis
      - cassandra
      - elasticsearch
    ports:
      - "6543:6543"
    volumes:
      - ../src/backend/configs:/etc/caliopen

  # ### Redis Database
  #
  # Used to store sessions.
  redis:
    image: redis
    ports:
        - "6379:6379"

  # ### Cassandra
  #
  # Cassandra is used as the reference storage for business data
  cassandra:
    image: scylladb/scylla
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7000:7000"
    volumes:
      - db:/var/lib/scylla
    entrypoint:
      - /docker-entrypoint.py
      - --memory
      - 512M

  # ### Elasticsearch
  #
  # Used to index mail content and ensure great research performances.
  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    volumes:
      - index:/usr/share/elasticsearch/data

  # Caliopen cli tool
  cli:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.cli
    image: caliopen_cli
    depends_on:
      - cassandra
      - elasticsearch
    environment:
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    volumes:
      - .:/srv/caliopen/src/backend/devtools
      - ../src/backend/configs:/etc/caliopen

    # Caliopen cli tool
  climl:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.cli-ml
    image: caliopen_climl
    depends_on:
      - cassandra
      - elasticsearch
      - objectstore
    volumes:
      - .:/srv/caliopen/src/backend/devtools
      - ../src/backend/configs:/etc/caliopen

  # Caliopen frontend
  frontend:
    build:
      context: ../src/frontend/web_application
    image: caliopen_frontend
    ports:
      - "4000:4000"
    depends_on:
      - proxyapi
    environment:
      CALIOPEN_API_HOSTNAME: proxyapi

  # Broker
  lmtpd:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.go-lmtp
    image: caliopen_lmtpd
    depends_on:
      - mqworker
      - smtp
      - imapworker
    ports:
      - "2525:2525"
    volumes:
      - ../src/backend/configs:/etc/caliopen

  # NATS
  nats:
    image: nats:1.4.0
    ports:
      - "4222:4222"
      - "8222:8222"

  # NATS Message Handler
  mqworker:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.mq-worker
    image: caliopen_mq_worker
    depends_on:
      - cassandra
      - elasticsearch
      - objectstore
      - nats
    volumes:
      - ../src/backend/configs:/etc/caliopen

  # object storage
  objectstore:
    image: minio/minio:latest
    ports:
      - "9090:9090"
    volumes:
      - ../src/backend/configs/minio:/etc/caliopen/minio
      - store:/export
    command:
      server --address :9090 -C /etc/caliopen/minio /export
    environment:
      - MINIO_ACCESS_KEY=CALIOPEN_ACCESS_KEY_
      - MINIO_SECRET_KEY=CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD

  # Worker for remote identities
  imapworker:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.imap-worker
    image: caliopen_imap_worker
    depends_on:
      - cassandra
      - objectstore
      - elasticsearch
      - nats
    volumes:
      - ../src/backend/configs:/etc/caliopen

  twitterworker:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.twitter-worker
    image: caliopen_twitter_worker
    depends_on:
    - cassandra
    - objectstore
    - elasticsearch
    - nats
    volumes:
    - ../src/backend/configs:/etc/caliopen

  # Poller for remote identities
  identitypoller:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.identity-poller
    image: caliopen_identity_poller
    depends_on:
      - imapworker
      - mqworker
      - nats
      - twitterworker
    volumes:
      - ../src/backend/configs:/etc/caliopen

  # Inbucket : a small smtp server to catch all outgoing emails for testing purpose
  # point your browser at localhost:8888
  smtp:
    image: jhillyerd/inbucket
    ports:
      - "8888:9000"
      - "2500:2500"

  kibana:
    image: kibana:5
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
