version: '2'
services:
  # Caliopen APIv2
  api:
      build:
        context: ../src/backend
        dockerfile: Dockerfile.go-api
      links:
          - apiv1:apiv1.dev.caliopen.org
          - redis:redis.dev.caliopen.org
          - cassandra:cassandra.dev.caliopen.org
          - nats:nats.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
          - object_store:minio.dev.caliopen.org
      ports:
          - "31415:31415"

  # Caliopen APIv1
  apiv1:
      build:
        context: ../src/backend
        dockerfile: Dockerfile.py-api
      links:
          - redis:redis.dev.caliopen.org
          - cassandra:cassandra.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
      ports:
          - "6543:6543"

  # ### Redis Database
  #
  # Used to store sessions.
  redis:
      image: redis
      ports:
          - "6379:6379"

  # ### Cassandra
  #
  # Cassandra is used as the reference storage for business data
  cassandra:
      image: scylladb/scylla
      ports:
          - "9042:9042"
          - "9160:9160"
          - "7000:7000"
      volumes:
          - .data/scylla:/var/lib/scylla
      entrypoint:
          - /docker-entrypoint.py
          - --memory
          - 512M

  # ### Elasticsearch
  #
  # Used to index mail content and ensure great research performances.
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
      ports:
          - "9200:9200"
      environment:
          - xpack.security.enabled=false
          - xpack.monitoring.enabled=false
      volumes:
          - .data/elasticsearch/data:/usr/share/elasticsearch/data

  # Caliopen cli tool
  cli:
      build:
        context: ../src/backend
        dockerfile: Dockerfile.cli
      links:
          - cassandra:cassandra.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
          - broker:broker.dev.caliopen.org
      environment:
          CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
      volumes:
        - .:/srv/caliopen/src/backend/devtools

  # Caliopen frontend
  frontend:
      build:
        context: ../src/frontend/web_application
      links:
          - api:api.dev.caliopen.org
      ports:
        - "4000:4000"
  # Broker
  broker:
      build:
        context: ../src/backend
        dockerfile: Dockerfile.go-lmtp
      links:
          - cassandra:cassandra.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
          - object_store:minio.dev.caliopen.org
          - nats:nats.dev.caliopen.org
          - message_handler:mc.dev.caliopen.org
          - inbucket:smtp.dev.caliopen.org
      ports:
        - "2525:2525"
  # NATS
  nats:
      image: nats:0.9.6
      ports:
          - "4222:4222"

  # NATS Message Handler
  message_handler:
      build:
        context: ../src/backend
        dockerfile: Dockerfile.message_handler
      links:
          - cassandra:cassandra.dev.caliopen.org
          - elasticsearch:es.dev.caliopen.org
          - nats:nats.dev.caliopen.org

  # object storage
  object_store:
    image: minio/minio
    ports:
      - "9090:9090"
    volumes:
        - ../src/backend/configs:/configs
        - .data/minio:/export
    command:
      server --address :9090 -C /configs/minio /export

  # Inbucket : a small smtp server to catch all outgoing emails for testing purpose
  # point your browser at localhost:8888
  inbucket:
      image: jhillyerd/inbucket
      ports:
          - "8888:10080"
          - "2500:10025"

  # Postfix : a complete smpt server that act as the Caliopen's MTA
  # TODO
