apiVersion: batch/v1
kind: Job
metadata:
  name: cli-setup
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
      - image: cli:new
        name: cli-setup
        imagePullPolicy: Never
        args: ["setup"]
        env:
        - name: CQLENG_ALLOW_SCHEMA_MANAGEMENT
          value: "1"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: caliopen.yaml
            path: caliopen.yaml