ApiConfig:
  listen_interface: 0.0.0.0
  listen_port: 6544
  hostname: http://localhost
  port: 6544
  BackendConfig:
    backend_name: cassandra
    backend_settings:
      hosts:
        - cassandra
      keyspace: caliopen
      consistency_level: 1
      raw_size_limit: 1048576                                # max size in bytes for objects in db. Use S3 interface if larger.
      object_store: s3
      object_store_settings:
        endpoint: objectstore:9090
        access_key: CALIOPEN_ACCESS_KEY_                     # Access key of 5 to 20 characters in length
        secret_key: CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD # Secret key of 8 to 40 characters in length
        location: eu-fr-localhost                            # S3 region.
        buckets:
          raw_messages: caliopen-raw-messages                # bucket name to put raw messages to
          temporary_attachments: caliopen-tmp-attachments    # bucket name to store draft attachments
      use_vault: false
      vault_settings:
        url: http://vault:8200
        username: api2                                       # password authentication for now ; later we'll make use of more secure auth methods (TLScert, kubernetesâ€¦)
        password: weak_password
  IndexConfig:
    index_name: elasticsearch
    index_settings:
      hosts:
        - http://elasticsearch:9200
  NatsConfig:
    url: nats://nats:4222
    nats_queue: NotifierQueue
    outSMTP_topic: outboundSMTP       # topic's name for "send" draft order via SMTP
    outIMAP_topic: outboundIMAP       # topic's name for "send" draft order via remote SMTP+IMAP
    outTWITTER_topic: twitter_dm      # topics's name for "send" draft order via TWITTER
    contacts_topic: contactAction     # topic's name to post messages regarding contacts' events
    keys_topic: keyAction             # topic's name to post messages regarding public key events
    users_topic: userAction           # topic's name to post messages regarding users events
    idpoller_topic: idCache           # topic's name to post messages to idpoller regarding identities management
  swaggerSpec: ./swagger.json #absolute path or relative path to go.server bin
  RedisConfig:
    host: redis:6379
    password: ""        #no password set
    db: 0               #use default db
  NotifierConfig:
    base_url: http://localhost:4000                         # url upon which to build custom links sent to users. NO trailing slash please.
    admin_username: admin                                   # username on whose behalf notifiers will act. This admin user must have been created before by other means.
    templates_path: "../defs/notifiers/templates/"          # path to yaml/j2 templates directory, WITH trailing slash please.
  Providers:                                                # temporary supported providers list for remote identities before moving this data into store facility
    - name: gmail
      protocol: email
      infos:
        client_id:
        client_secret:
        imapserver: imap.gmail.com:993
        smtpserver: smtp.gmail.com:587
    - name: twitter
      protocol: twitter
      infos:
        consumer_key:
        consumer_secret:
ProxyConfig:
  listen_interface: 0.0.0.0
  port: 31415
  routes:
    - /api/v2/: localhost:6544
    - /: apiv1:3001         # route "/" catch all other requests

