# Caliopen configuration file to run REST API server in a docker container
#
# Storage services must be accessible using FQDN:
#  - cassandra.dev.caliopen.org
#  - es.dev.caliopen.org
#  - redis.dev.caliopen.org (see pyramid configuration file)
#
# Make your /etc/hosts lie or user docker containers from docker-compose.yml in /devtools

delivery_agent:
    direct: True

elasticsearch:
    url: http://elasticsearch:9200
    mappings_version: v6
    shards:
        - caliopen-dev-0001
        - caliopen-dev-0002
        - caliopen-dev-0003
        - caliopen-dev-0004

cassandra:
    keyspace: caliopen
    hosts:
        - 'cassandra'
    consistency_level: 1
    protocol_version: 3

lmtp:
    port: 4025
    bind_address: 0.0.0.0

broker:
    port: 2525
    host: broker

message_queue:
    port: 4222
    host: nats

object_store:
    db_size_limit: 1048576
    service: s3
    endpoint: objectstore:9090
    access_key: CALIOPEN_ACCESS_KEY_
    secret_key: CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD
    location: eu-fr-localhost

system:
    max_users: 100
    default_tags:
        -
            name: inbox
        -
            name: spam
        -
            name: important
            importance_level: 5
        -
            name: internal
            label: Caliopen
            importance_level: 2

default_domain: caliopen.local

internal_domains:
    - caliopen.local
    - brainstorm.fr

blacklistes:
    mx:
        - mx.bad.guy

key_discovery:
    dns:
        enable: True
        name_server: 8.8.8.8
    hkp:
        enable: True
