ApiConfig:
  host: 127.0.0.1
  port: 6544
  BackendConfig:
    backend_name: cassandra
    backend_settings:
      hosts:
      - 127.0.0.1
      keyspace: caliopen
      consistency_level: 1
  NatsConfig:
    url: nats://localhost:4222
    outSMTP_topic: outboundSMTP # topic's name to post "send" draft order
  swaggerSpec: ../../../../../../../doc/api/swagger.json #absolute path or relative path to go.server bin
  RedisConfig:
    host: localhost:6379
    password: ""      #no password set
    db: 0             #use default db
ProxyConfig:
  host: 127.0.0.1
  port: 31415
  routes:
  - /api/v2/: 127.0.0.1:6544
  - /: 127.0.0.1:6543         # route "/" catch all other requests
