#polling config
scan_interval: 15                               # in minutes. How often storage is scanned to retrieve and cache remote identities data
remote_types:                                   # which kind of remote identities poller must handle
  - imap
#storage facility
store_name: cassandra                           # backend for remote identities data
store_settings:
  hosts: # many allowed
  - cassandra.dev.caliopen.org
  keyspace: caliopen
  consistency_level: 1
#messaging system
nats_url: nats://nats.dev.caliopen.org:4222
nats_queues:                                    # NATS group queue for each kind of remote identities
  imap: IMAPworkers
nats_topics:                                    # NATS topic to listen to actions to execute
  imap: IMAPfetcher
