workers: 2                                             # number of concurrent workers
#messaging system
nats_url: nats://nats.dev.caliopen.org:4222
nats_queue: IMAPworkers                                # NATS group queue for workers
nats_topic: IMAPfetcher                                # NATS topic to listen to actions to execute
#storage facility
store_name: cassandra                                  # backend to store raw emails and messages (inbound & outbound)
store_settings:
  hosts: # many allowed
  - cassandra.dev.caliopen.org
  keyspace: caliopen
  consistency_level: 1
  raw_size_limit: 1048576                                 # max size in bytes for objects in db. Use S3 interface if larger.
  object_store: s3
  object_store_settings:
    endpoint: minio.dev.caliopen.org:9090
    access_key: CALIOPEN_ACCESS_KEY_                     # Access key of 5 to 20 characters in length
    secret_key: CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD # Secret key of 8 to 40 characters in length
    location: eu-fr-localhost                            # S3 region.
    buckets:
      raw_messages: caliopen-raw-messages                # bucket name to put raw messages to
      temporary_attachments: caliopen-tmp-attachments    # bucket name to store draft attachments
  use_vault: false
  vault_settings:
    url: http://127.0.0.1:8200
    username: imapworker                                 # password authentication for now ; later we'll make use of more secure auth methods (TLScert, kubernetes…)
    password: a_weak_password
LDAConfig:
  broker_type: imap                                      # types are : smtp, imap, mailboxe, etc.
  lda_workers_size: 2                                    # number of concurrent workers
  log_received_mails: true
  #index facility
  index_name: elasticsearch                              # backend to index messages (inbound & outbound)
  index_settings:
    urls: # many allowed
    - http://es.dev.caliopen.org:9200
  #messaging system
  in_topic: inboundSMTP # NATS topic to listen to
  nats_queue: SMTPqueue
  # notifications
  NotifierConfig:
    admin_username: admin                                # username on whose behalf notifiers will act. This admin user must have been created before by other means.
