## SMTP config ##
AppConfig:
  allowed_hosts:
  - localhost
  - caliopen.local
  - caliopen.org
  - cluster.local
  primary_mail_host: caliopen.org
  inbound_servers: # only one allowed for now
  - is_enabled: true
    host_name: localhost
    max_size: 20971520                                   # max authorized size for emails in bytes
    timeout: 180
    listen_interface: 0.0.0.0:2525
    start_tls_on: false
    tls_always_on: false
    max_clients: 1000
  #submit is the MTA to connect to for final delivery (postfix for example)
  submit_address: smtp
  submit_port: 2500
  submit_user:
  submit_password:
  submit_workers: 2                                      # number of concurrent connexions to submit MTA

## LDA (Email broker) config ##
LDAConfig:
  broker_type: smtp                                      # types are : smtp, imap, mailboxe, etc.
  nats_url: nats://nats:4222
  nats_queue: SMTPqueue                                  # NATS group queue for nats subscribers to share jobs
  store_name: cassandra                                  # backend to store raw emails and messages (inbound & outbound)
  store_settings:
    hosts: # many allowed
    - cassandra
    keyspace: caliopen
    consistency_level: 1
    raw_size_limit: 1048576                              # max size in bytes for objects in db. Use S3 interface if larger.
    object_store: s3
    object_store_settings:
      endpoint: objectstore:9090
      access_key: CALIOPEN_ACCESS_KEY_                     # Access key of 5 to 20 characters in length
      secret_key: CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD # Secret key of 8 to 40 characters in length
      location: eu-fr-localhost                            # S3 region.
      buckets:
        raw_messages: caliopen-raw-messages                # bucket name to put raw messages to
        temporary_attachments: caliopen-tmp-attachments    # bucket name to store draft attachments
    use_vault: false
    vault_settings:
      url: http://vault:8200
      username: lmtpd                                    # password authentication for now ; later we'll make use of more secure auth methods (TLScert, kubernetes…)
      password: still_a_weak_password
  index_name: elasticsearch                              # backend to index messages (inbound & outbound)
  index_settings:
    urls: # many allowed
    - http://elasticsearch:9200

  #inbound
  in_topic: inboundSMTP                                  # NATS topic to listen to
  lda_workers_size: 2                                    # number of concurrent workers
  log_received_mails: true

  # outbound
  out_topic: outboundSMTP                                # NATS topic to listen to
  nats_listeners: 2                                      # number of concurrent nats listeners

  # notifications
  contacts_topic: contactAction                             # topic's name to post messages regarding contacts' events
  NotifierConfig:
    base_url: http://localhost:4000                         # url upon which to build custom links sent to users. NO trailing slash please.
    admin_username: admin                                   # username on whose behalf notifiers will act. This admin user must have been created before by other means.
    templates_path: "../defs/notifiers/templates/"          # path to yaml/j2 templates directory, WITH trailing slash please.