ApiConfig:
  host: 127.0.0.1
  port: 6544
  BackendConfig:
    backend_name: cassandra
    backend_settings:
      hosts:
      - cassandra
      keyspace: caliopen
      consistency_level: 1
      raw_size_limit: 1048576                                # max size in bytes for objects in db. Use S3 interface if larger.
      object_store: s3
      object_store_settings:
        endpoint: minio:9090
        access_key: CALIOPEN_ACCESS_KEY_                     # Access key of 5 to 20 characters in length
        secret_key: CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD # Secret key of 8 to 40 characters in length
        location: eu-fr-localhost                            # S3 region.
        buckets:
          raw_messages: caliopen-raw-messages                # bucket name to put raw messages to
          temporary_attachments: caliopen-tmp-attachments    # bucket name to store draft attachments
  IndexConfig:
    index_name: elasticsearch
    index_settings:
      hosts:
      - http://elasticsearch:9200
  NatsConfig:
    url: nats://nats:4222
    outSMTP_topic: outboundSMTP     # topic's name to post "send" draft order
    contacts_topic: contactAction   # topic's name to post messages regarding contacts' events
  swaggerSpec: ../doc/api/swagger.json #absolute path or relative path to go.server bin
  RedisConfig:
    host: redis:6379
    password: ""        #no password set
    db: 0               #use default db
  NotifierConfig:
    base_url: http://localhost:4000                         # url upon which to build custom links sent to users. NO trailing slash please.
    admin_username: admin                                   # username on whose behalf notifiers will act. This admin user must have been created before by other means.
    templates_path: "../defs/notifiers/templates/"          # path to yaml/j2 templates directory, WITH trailing slash please.
ProxyConfig:
  host: 0.0.0.0
  port: 31415
  routes:
  - /api/v2/: 127.0.0.1:6544
  - /: apiv1:6543         # route "/" catch all other requests

