apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  #strategy:
  #  type: Recreate / RollingUpdate
  #    maxUnavailable:
  template:
    metadata:
      labels:
        type: api
        tier: backend
        app: api
    spec:
      containers:
      - image: api:new
        imagePullPolicy: Never
        name: api
        ports:
        - containerPort: 31415
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: apiv2.yaml
            path: apiv2.yaml
          - key: swagger.json
            path: swagger.json
      restartPolicy: Always