apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        type: index
        tier: backend
        app: elasticsearch
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
        name: elasticsearch
        ports:
        - containerPort: 9200
        env:
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.monitoring.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms512M -Xmx512M"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: dev-index
      restartPolicy: Always
      volumes:
      - name: dev-index
        persistentVolumeClaim:
          claimName: dev-index

